# Generated by Django 5.0.6 on 2024-06-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carousel", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="students",
            new_name="carousel",
        ),
    ]
